version: '3.9'

services:
  bingo_app:
    container_name: bingo_app
    image: bingo-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      DATA_SOURCE_URL: jdbc:postgresql://bingo_db:5432/bingo
      DATA_SOURCE_USERNAME: root
      DATA_SOURCE_PASSWORD: root
    depends_on:
      - bingo_db
  bingo_db:
    container_name: bingo_db
    image: postgres:13.15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bingo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root