spring.application.name=bingo-app

spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USERNAME}
spring.datasource.password=${DATA_SOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.slq-show=true
spring.jpa.open-in-view=false
spring.devtools.add-properties=false
logging.level.web=ERROR
